# ==========================================================================
# Raw variable passthrough: {{id}}
# --------------------------------------------------------------------------
# GENERATED by the variable atlas on {{created}}. This is not a harmonised
# variable and it is not part of the harmonisation repository - it carries
# one raw column out of one deposited file, unchanged.
#
# It is written as an ordinary variable script on purpose. R/runner.R then
# does all the work that makes the column usable and comparable with the
# harmonised ones beside it: resolving the file through
# master_file_info_lookup.csv, normalising the identifier column and its
# values, dropping unlinkable rows, resolving duplicate identifiers against
# the columns actually retained, and joining the result to every other
# variable in the bundle on bcsid. None of that is reimplemented here, so a
# passthrough cannot drift away from the tested pipeline.
#
# What it does NOT do is recode anything. The values you get are the codes
# as deposited, missing-value sentinels included - look them up in the data
# dictionary for {{file}} before you analyse them. If you find yourself
# writing that recoding by hand, that is the point at which it is worth
# requesting a harmonised variable instead, so everyone gets the same one.
#
# Placeholders below are filled in by web/bundle.js.
# ==========================================================================

spec <- list(
  id = "{{id}}",
  label = "{{label}}",
  # Passthroughs are not harmonised, but every script must declare one of the
  # fixed categories and sit under a matching directory - see
  # R/lib/discovery.R. "other" is the honest answer for a raw column.
  category = "other",
  github_issue = NA,
  status = "raw_passthrough", # not on the draft -> verified track: nothing was derived
  author = NA,
  created = "{{created}}",
  source_files = c("{{file}}"),
  source_vars = c("{{var}}"),
  notes = "Raw {{wave}} column {{var}} from {{file}}, passed through unchanged by the variable atlas. Values are as deposited - not recoded, and missing-value sentinels not removed."
)

derive <- function(data) {
  # Built by assignment rather than as a data.frame(...) argument because
  # neither the raw name nor the output name is guaranteed to be a syntactic
  # R name: load_tab() reads with check.names = FALSE, so a deposited column
  # can be called anything at all.
  out <- data.frame(bcsid = data$bcsid, stringsAsFactors = FALSE)
  out[["{{id}}"]] <- data[["{{var}}"]]
  out
}
