# Raw passthrough: {{id}}
# Generated by the variable atlas on {{created}}. Not a harmonised variable and
# not part of the harmonisation repository.
#
# It is an ordinary variable script on purpose, so R/runner.R does the file
# resolution, identifier cleaning, duplicate resolution and the join for it
# exactly as it does for a derived one. Nothing is reimplemented here.
#
# It does NOT recode. The values are the codes as deposited, missing-value
# sentinels included - look them up in the data dictionary for {{file}} before
# analysing them. If you find yourself recoding this by hand, that is the point
# to request a harmonised variable instead.

spec <- list(
  id = "{{id}}",
  label = "{{label}}",
  # Not harmonised, but every script must declare one of the fixed categories
  # and sit under a matching directory - see R/lib/discovery.R.
  category = "other",
  github_issue = NA,
  status = "raw_passthrough",
  author = NA,
  created = "{{created}}",
  source_files = c("{{file}}"),
  source_vars = c("{{var}}"),
  notes = "Raw {{wave}} column {{var}} from {{file}}, passed through unchanged. Values are as deposited - not recoded, sentinels not removed."
)

derive <- function(data) {
  # Built by assignment because load_tab() reads with check.names = FALSE, so
  # neither name is guaranteed to be a syntactic R name.
  out <- data.frame(id = data[["{{identifier}}"]], stringsAsFactors = FALSE)
  names(out) <- "{{identifier}}"
  out[["{{id}}"]] <- data[["{{var}}"]]
  out
}
